import { CalendarRange, Download, Expand, Folder, Link2, MessageSquare, Minimize2, PanelLeft, PanelRightClose, PanelRightOpen, Paperclip, Phone, Plus, Search, SearchCheck, Send, Trash2, X } from "lucide-react";
import { FormEvent, ReactNode, useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { ApiError, api } from "../../api";
import type { AssistantCapabilities, AssistantChat, AssistantMessage, ContentSearchItem } from "../../types";
import { ChoiceMenu, ToolButton } from "./AssistantControls";
import { AssistantContextPicker, ContextItem } from "./AssistantContextPicker";

type Detail="brief"|"auto"|"detailed";
type Panel="sources"|"attachments";
const panelOptions=[{id:"sources",Icon:Link2,label:"Источники"},{id:"attachments",Icon:Paperclip,label:"Вложения"}] as const;
const time=(value:string)=>{const date=new Date(value);return Number.isNaN(date.valueOf())?"":new Intl.DateTimeFormat("ru-RU",{hour:"2-digit",minute:"2-digit"}).format(date)};
const mentionTerm=(value:string)=>/(?:^|\s)@([^\s]*)$/.exec(value)?.[1]??"";

function linkedSourceText(text:string) {
 const ordinals=new Map<string,number>();
 const link=(source:string)=>{if(!ordinals.has(source))ordinals.set(source,ordinals.size+1);const ordinal=ordinals.get(source)!;return `[источник ${ordinal}](#assistant-source-${ordinal})`};
 return text.replace(/\(?\s*подтверждается\s+(S\d+)\s*\)?/gi,(_,source:string)=>link(source.toUpperCase())).replace(/\b(S\d+)\b/g,(_,source:string)=>link(source.toUpperCase()))
}
function AssistantMarkdownMessage({text,animate,onSource}:{text:string;animate:boolean;onSource:(ordinal:number)=>void}) {
 const parts=useMemo(()=>linkedSourceText(text).split(/(\s+)/),[text]);
 const [visible,setVisible]=useState(animate?0:parts.length);
 useEffect(()=>{
  if(!animate){setVisible(parts.length);return}
  setVisible(0);
  const timer=window.setInterval(()=>setVisible(current=>{const next=Math.min(parts.length,current+2);if(next>=parts.length)window.clearInterval(timer);return next}),28);
  return()=>window.clearInterval(timer)
 },[animate,parts]);
 return <><ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({href,children})=>{const match=/^#assistant-source-(\d+)$/.exec(href??"");return match?<button type="button" className="assistant-inline-source" onClick={()=>onSource(Number(match[1]))}>{children}</button>:<a href={href}>{children}</a>}}}>{parts.slice(0,visible).join("")}</ReactMarkdown>{animate&&visible<parts.length&&<span className="assistant-stream-caret" aria-hidden="true"/>}</>
}

export function AssistantWorkspace({companyId,companies,onOpenCall,open,setOpen}:{companyId:string;companies:{id:string;name:string}[];onOpenCall:(id:string)=>void;open:boolean;setOpen:(value:boolean)=>void}) {
 const [scope,setScope]=useState<"personal"|"company">("personal");
 const [expanded,setExpanded]=useState(false);
 const [drafts,setDrafts]=useState<Record<string,string>>({});
 const [chosenCompany,setChosenCompany]=useState(companyId);
 const selected=companies.find(c=>c.id===chosenCompany)??companies.find(c=>c.id===companyId)??companies[0];
 const activeCompany=scope==="company"?selected?.id??"":"";
 const scopeKey=activeCompany||"personal";
 const scopeControl=companies.length>0?<div className="assistant-scope-bar"><div className={`assistant-scope-switch ${activeCompany?"is-company":""}`} role="group" aria-label="Контекст и плательщик"><span aria-hidden="true" className="assistant-scope-thumb"/><button type="button" aria-pressed={!activeCompany} onClick={()=>setScope("personal")}>Личные звонки</button><button type="button" aria-pressed={!!activeCompany} onClick={()=>setScope("company")}>Компания</button></div>{activeCompany&&companies.length>1&&<ChoiceMenu label="Компания" value={activeCompany} options={companies.map(c=>({value:c.id,label:c.name}))} onChange={setChosenCompany}/>}</div>:null;
 return <ScopedAssistantWorkspace key={scopeKey} companyId={activeCompany} onOpenCall={onOpenCall} open={open} setOpen={setOpen} expanded={expanded} setExpanded={setExpanded} scopeControl={scopeControl} query={drafts[scopeKey]??""} setQuery={value=>setDrafts(previous=>({...previous,[scopeKey]:value}))}/>;
}
function ScopedAssistantWorkspace({companyId,onOpenCall,open,setOpen,expanded,setExpanded,scopeControl,query,setQuery}:{companyId:string;onOpenCall:(id:string)=>void;open:boolean;setOpen:(value:boolean)=>void;expanded:boolean;setExpanded:(value:boolean)=>void;scopeControl:ReactNode;query:string;setQuery:(value:string)=>void}) {
 const [cap,setCap]=useState<AssistantCapabilities|null>(null);
 const [chats,setChats]=useState<AssistantChat[]>([]),[chat,setChat]=useState<AssistantChat|null>(null),[messages,setMessages]=useState<AssistantMessage[]>([]);
 const [results,setResults]=useState<ContentSearchItem[]>([]),[warnings,setWarnings]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [detail,setDetail]=useState<Detail>("auto"),[panel,setPanel]=useState<Panel|null>("sources"),[historyOpen,setHistoryOpen]=useState(false),[pickerOpen,setPickerOpen]=useState(false);
 const [context,setContext]=useState<ContextItem[]>([]),[period,setPeriod]=useState<{from:string;to:string}|null>(null),[deleting,setDeleting]=useState<string|null>(null);
 const [draftVersion,setDraftVersion]=useState(0),[draftLoaded,setDraftLoaded]=useState(false),[draftState,setDraftState]=useState<"saved"|"saving"|"conflict">("saved");
 const textarea=useRef<HTMLTextAreaElement>(null),scroll=useRef<HTMLDivElement>(null);
 const retry=useRef<{signature:string;chatId:string;key:string;clientId:string}|null>(null);
 const openRef=useRef(open);
 const animatedAssistantIds=useRef(new Set<string>());
 const [streamingMessageId,setStreamingMessageId]=useState("");
 const [highlightedSource,setHighlightedSource]=useState(0);
 const draftTimer=useRef<number|null>(null);
 const pendingDraftTransfer=useRef<{chatId:string;items:ContextItem[];period:{from:string;to:string}|null}|null>(null);
 const closePicker=useCallback(()=>setPickerOpen(false),[]);
 useEffect(()=>{openRef.current=open;if(!open)setStreamingMessageId("")},[open]);
 useEffect(()=>{let alive=true;api.assistantCapabilities(companyId).then(v=>{if(alive)setCap(v)}).catch(()=>{if(alive)setError("Не удалось проверить доступ к выбранному контексту.")});return()=>{alive=false}},[companyId]);
 useEffect(()=>{if(!open||!cap?.chat_enabled)return;let alive=true;api.listAssistantChats(companyId).then(v=>{if(alive)setChats(v.items)}).catch(()=>{if(alive)setError("Не удалось загрузить список чатов")});return()=>{alive=false}},[open,cap?.chat_enabled,companyId]);
 useEffect(()=>{if(!chat)return;let alive=true;api.listAssistantMessages(chat.id).then(v=>{if(alive){setMessages(v.items);v.items.filter(item=>item.role==="assistant").forEach(item=>animatedAssistantIds.current.add(item.id))}}).catch(()=>{if(alive)setError("Не удалось загрузить переписку")});return()=>{alive=false}},[chat?.id]);
 useEffect(()=>{if(!cap?.chat_enabled){setDraftLoaded(false);return}let alive=true;const activeChatId=chat?.id;setDraftLoaded(false);api.getAssistantDraft(companyId,activeChatId).then(async value=>{if(!alive)return;const transfer=activeChatId&&pendingDraftTransfer.current?.chatId===activeChatId?pendingDraftTransfer.current:null;if(transfer){const saved=await api.saveAssistantDraft({company_uuid:companyId,chat_uuid:activeChatId,text:"",context:{items:transfer.items,period:transfer.period},lock_version:value.lock_version});if(!alive)return;pendingDraftTransfer.current=null;setQuery("");setContext(transfer.items);setPeriod(transfer.period);setDraftVersion(saved.lock_version)}else{setQuery(value.text);setContext(value.context?.items??[]);setPeriod(value.context?.period??null);setDraftVersion(value.lock_version)}setDraftState("saved");setDraftLoaded(true)}).catch(()=>{if(alive){setDraftLoaded(true);setError("Не удалось восстановить черновик")}});return()=>{alive=false}},[companyId,chat?.id,cap?.chat_enabled]);
 useEffect(()=>{if(!draftLoaded)return;if(draftTimer.current)window.clearTimeout(draftTimer.current);draftTimer.current=window.setTimeout(()=>{api.saveAssistantDraft({company_uuid:companyId,chat_uuid:chat?.id,text:query,context:{items:context,period},lock_version:draftVersion}).then(value=>{setDraftVersion(value.lock_version);setDraftState("saved")}).catch(cause=>{if(cause instanceof ApiError&&cause.status===409){setDraftState("conflict");setError("Черновик изменён в другом окне. Ваш текст сохранён здесь; создайте новый чат, чтобы не перезаписать изменения.")}else{setDraftState("conflict")}})},1000);return()=>{if(draftTimer.current)window.clearTimeout(draftTimer.current)}},[companyId,chat?.id,query,context,period,draftLoaded]);
 useLayoutEffect(()=>{const node=textarea.current;if(!node)return;node.style.height="0px";node.style.height=`${Math.min(176,Math.max(38,node.scrollHeight))}px`;node.style.overflowY=node.scrollHeight>176?"auto":"hidden"},[query,open,expanded]);
 useEffect(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight},[messages,results,busy]);
 useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!pickerOpen){setOpen(false)}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[open,pickerOpen,setOpen]);
 const sources=useMemo(()=>[...new Map(messages.flatMap(m=>m.sources??[]).map(s=>[s.id,s])).values()],[messages]);
 const filters=useMemo(()=>{const callIds=[...new Set(context.flatMap(c=>c.kind==="call"?[c.id]:c.kind==="chat"?c.callIds??[]:[]))];const folderIds=context.filter(c=>c.kind==="folder").map(c=>c.id);let from:string|undefined,to:string|undefined;if(period){from=new Date(`${period.from}T00:00:00`).toISOString();const end=new Date(`${period.to}T00:00:00`);end.setDate(end.getDate()+1);to=end.toISOString()}return {call_uuids:callIds.length?callIds:undefined,folder_uuids:folderIds.length?folderIds:undefined,from,to}},[context,period]);
 function newChat(){if(busy)return;setError("");setChat(null);setMessages([]);setResults([]);setWarnings([]);setQuery("");setContext([]);setPeriod(null);retry.current=null;setHistoryOpen(false);textarea.current?.focus()}
 async function removeChat(id:string){if(busy)return;setDeleting(id);setError("");try{await api.deleteAssistantChat(id);setChats(v=>v.filter(c=>c.id!==id));if(chat?.id===id){setChat(null);setMessages([]);retry.current=null}}catch{setError("Не удалось удалить чат. Дождитесь завершения активного запроса и повторите.")}finally{setDeleting(null)}}
 async function exportChat(){if(!chat)return;setError("");try{const blob=await api.exportAssistantChat(chat.id);const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`${chat.title.replace(/[\\/:*?\"<>|]/g,"-")||"исследование"}.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0)}catch{setError("Не удалось экспортировать исследование. Проверьте доступ тарифа.")}}
 function addContext(item:ContextItem){setContext(v=>v.some(c=>c.kind===item.kind&&c.id===item.id)?v:[...v,item]);setQuery(query.replace(/(?:^|\s)@[^\s]*$/," ").trimStart());setPickerOpen(false);textarea.current?.focus()}
 function showSource(ordinal:number){setExpanded(true);setPanel("sources");setHighlightedSource(ordinal);window.setTimeout(()=>document.getElementById(`assistant-source-${ordinal}`)?.scrollIntoView({behavior:"smooth",block:"center"}),60);window.setTimeout(()=>setHighlightedSource(current=>current===ordinal?0:current),1400)}
 async function submit(event:FormEvent){event.preventDefault();const text=query.trim();if(text.length<2||busy||!cap?.search_enabled)return;const draftChatId=chat?.id;const sentContextLabels=[...context.map(item=>item.label),...(period?[`${period.from} — ${period.to}`]:[])];const optimisticId=crypto.randomUUID();const optimistic:AssistantMessage={id:optimisticId,chat_uuid:chat?.id??"",sequence:messages.length+1,role:"user",status:"completed",text,blocks:sentContextLabels.length?[{type:"context",data:{labels:sentContextLabels}}]:[],sources:[],created_at:new Date().toISOString()};if(cap.chat_enabled)setMessages(v=>[...v,optimistic]);if(draftTimer.current)window.clearTimeout(draftTimer.current);setDraftLoaded(false);setQuery("");setBusy(true);setError("");setWarnings([]);
 try{if(!cap.chat_enabled){const value=await api.contentSearch(companyId,text,filters);setResults(value.items);setWarnings(value.warnings);return}
 let active=chat;if(!active){active=await api.createAssistantChat(companyId,detail);pendingDraftTransfer.current={chatId:active.id,items:[...context],period};setChat(active);setChats(v=>[active!,...v])}
 const signature=JSON.stringify({text,detail,filters});if(!retry.current||retry.current.signature!==signature||retry.current.chatId!==active.id)retry.current={signature,chatId:active.id,key:crypto.randomUUID(),clientId:crypto.randomUUID()};const attempt=retry.current;
 const local:AssistantMessage={...optimistic,id:attempt.clientId,chat_uuid:active.id};setMessages(v=>v.map(m=>m.id===optimisticId?local:m));
 let run=await api.createAssistantMessage(active.id,{company_uuid:companyId,text,response_detail:detail,idempotency_key:attempt.key,client_message_id:attempt.clientId,context_labels:sentContextLabels,...filters});
 for(let poll=0;poll<120&&!(["completed","partial","failed","cancelled","access_revoked"].includes(run.state));poll++){await new Promise(resolve=>window.setTimeout(resolve,1000));run=await api.getAssistantRun(run.id)}
 const refreshed=await api.listAssistantMessages(active.id);const nextAssistant=[...refreshed.items].reverse().find(item=>item.role==="assistant"&&!animatedAssistantIds.current.has(item.id));setMessages(refreshed.items);if(nextAssistant){animatedAssistantIds.current.add(nextAssistant.id);if(openRef.current&&document.visibilityState==="visible")setStreamingMessageId(nextAssistant.id)}const history=await api.listAssistantChats(companyId);setChats(history.items);
 if(run.state==="completed"||run.state==="partial"){retry.current=null;setDraftState("saved")}else{setError(run.error_code?`Не удалось завершить запрос: ${run.error_code}. Повторите попытку.`:"Ответ ещё обрабатывается. Он появится в этом чате после завершения.")}
 }catch{setMessages(v=>v.filter(message=>message.id!==optimisticId));setQuery(text);setError("Не удалось завершить запрос. Текст восстановлен — повторная отправка сохранит ключ этой попытки.")}finally{setDraftLoaded(true);setBusy(false)}}
 if(!open)return null;
 return <section className={`assistant-workspace ${expanded?"is-expanded":""} ${historyOpen?"has-history-open":""}`} aria-label="Поиск и помощник по звонкам">
 {cap?.chat_enabled&&<aside className={`assistant-history ${historyOpen?"is-open":""}`} aria-hidden={!historyOpen}><header><strong>Чаты</strong><ToolButton label="Новый чат" disabled={busy||!historyOpen} onClick={newChat}><Plus size={17}/></ToolButton></header><div className="assistant-history-list">{chats.length?chats.map(c=><div className={`assistant-chat-row ${chat?.id===c.id?"active":""}`} key={c.id}><button type="button" tabIndex={historyOpen?0:-1} disabled={busy||!historyOpen} onClick={()=>{setChat(c);setMessages([]);if(expanded)setHistoryOpen(false);retry.current=null}}><MessageSquare size={15}/><span>{c.title}</span></button><ToolButton label={`Удалить чат «${c.title}»`} disabled={busy||deleting===c.id||!historyOpen} onClick={()=>void removeChat(c.id)}><Trash2 size={14}/></ToolButton></div>):<p>Здесь появятся ваши исследования.</p>}</div></aside>}
 <header className="assistant-header">{cap?.chat_enabled&&<ToolButton className="assistant-history-toggle" label={historyOpen?"Скрыть историю":"История чатов"} aria-pressed={historyOpen} onClick={()=>setHistoryOpen(value=>!value)}><PanelLeft size={17}/></ToolButton>}<div className="assistant-brand"><SearchCheck size={21}/><div><strong>Работа со звонками</strong><small>{cap?.chat_enabled?"Поиск и исследование":"Поиск по доступным записям"}</small></div></div>{scopeControl}<div className="assistant-head-actions">{chat&&messages.length>0&&cap?.export_enabled&&<ToolButton label="Скачать исследование" onClick={()=>void exportChat()}><Download size={17}/></ToolButton>}<ToolButton className="assistant-expand-action" label={expanded?"Компактный вид":"Развернуть"} onClick={()=>setExpanded(!expanded)}>{expanded?<Minimize2 size={17}/>:<Expand size={17}/>}</ToolButton><ToolButton label="Свернуть помощника" onClick={()=>setOpen(false)}><X size={17}/></ToolButton></div></header>
 <div className="assistant-body">
 {cap?.chat_enabled&&!historyOpen&&<div className="assistant-history-launch"><ToolButton label="Новый чат" onClick={newChat}><Plus size={17}/></ToolButton></div>}
 <main className="assistant-conversation"><div className="assistant-context"><span><Link2 size={14}/>{context.length?`Материалов: ${context.length}`:"Все доступные звонки"}{period&&<CalendarRange size={14}/>}</span>{cap?.chat_enabled&&<ChoiceMenu label="Размер ответа" value={detail} options={[{value:"brief",label:"Кратко"},{value:"auto",label:"Автоматически"},{value:"detailed",label:"Подробно"}]} onChange={v=>setDetail(v as Detail)}/>}</div>
 <div ref={scroll} className="assistant-scroll" aria-live="polite">{cap&&!cap.search_enabled&&<p className="assistant-error">В этом контексте нет доступа или активной подписки. Переключите контекст в хедере.</p>}{(cap?.chat_enabled?messages:results).length===0&&<div className="assistant-empty"><Search size={28}/><strong>Найдите ответ в разговорах</strong><p>Найдите нужную запись или добавьте материалы через <b>+</b> и <b>@</b>, чтобы уточнить контекст.</p></div>}
 {cap?.chat_enabled?messages.map(m=>{const labels=m.blocks?.find(block=>block.type==="context")?.data?.labels??[];return <article key={m.id} className={`assistant-message ${m.role}`}>{labels.length?<div className="assistant-message-context" aria-label="Вложения сообщения">{labels.map(label=><span key={label}><Paperclip size={12}/>{label}</span>)}</div>:null}<div>{m.role==="assistant"?<AssistantMarkdownMessage text={m.text} animate={m.id===streamingMessageId} onSource={showSource}/>:m.text}</div><footer><time dateTime={m.created_at}>{time(m.created_at)}</time>{m.sources?.length>0&&<button type="button" onClick={()=>showSource(1)}>Источники · {m.sources.length}</button>}</footer></article>}):results.map(r=><button type="button" className="assistant-result" key={r.chunk_uuid} onClick={()=>onOpenCall(r.call_uuid)}><strong>{r.title}</strong><p>{r.quote}</p><small>{r.source_kind==="analysis"?"Анализ":r.speaker||"Транскрипция"} · Версия {r.transcription_revision} · {new Date(r.updated_at).toLocaleDateString("ru-RU")}</small></button>)}
 {warnings.map(w=><p className="assistant-notice" key={w}>{w}</p>)}{busy&&<p className="assistant-progress"><span className="assistant-spinner"/>Обработка запроса…</p>}{error&&<p className="assistant-error" role="alert">{error}</p>}
 </div>
 <form onSubmit={submit} className="assistant-compose-area">{(context.length>0||period)&&<div className="assistant-context-chips">{context.map(c=><span key={`${c.kind}:${c.id}`}>{c.kind==="call"?<Phone size={13}/>:c.kind==="folder"?<Folder size={13}/>:<MessageSquare size={13}/>}<span>{c.label}</span><button type="button" aria-label={`Убрать ${c.label}`} onClick={()=>setContext(v=>v.filter(x=>x!==c))}><X size={12}/></button></span>)}{period&&<span><CalendarRange size={13}/>{period.from} — {period.to}<button type="button" aria-label="Убрать период" onClick={()=>setPeriod(null)}><X size={12}/></button></span>}</div>}
 {pickerOpen&&<AssistantContextPicker companyId={companyId} searchTerm={mentionTerm(query)} onClose={closePicker} onSelect={addContext} onPeriod={(from,to)=>setPeriod({from,to})}/>}
 <div className="assistant-composer"><ToolButton label="Добавить материалы (@)" aria-expanded={pickerOpen} onClick={()=>setPickerOpen(v=>!v)}><Plus size={20}/></ToolButton><textarea ref={textarea} aria-label="Запрос по звонкам" value={query} onChange={e=>{const value=e.target.value;setQuery(value);setDraftState("saving");setPickerOpen(/(?:^|\s)@[^\s]*$/.test(value))}} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing&&!pickerOpen){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} placeholder="Спросите о звонках…" rows={1} maxLength={12000}/><button type="submit" className="assistant-send" disabled={busy||query.trim().length<2||!cap?.search_enabled} aria-label="Отправить запрос"><Send size={18}/></button></div><small>Ответ учитывает доступные данные на момент запроса.{query&&draftState==="saving"?" · Сохранение черновика…":query&&draftState==="conflict"?" · Черновик сохранён только в этом окне":""}</small></form>
 </main>
 {expanded&&<aside className={`assistant-inspector ${panel?"":"is-collapsed"}`}><nav aria-label="Материалы исследования">{panelOptions.map(({id,Icon,label})=><ToolButton key={id} label={label} aria-pressed={panel===id} onClick={()=>setPanel(v=>v===id?null:id)}><Icon size={17}/></ToolButton>)}<ToolButton label={panel?"Свернуть правую панель":"Развернуть правую панель"} onClick={()=>setPanel(v=>v?null:"sources")}>{panel?<PanelRightClose size={17}/>:<PanelRightOpen size={17}/>}</ToolButton></nav>{panel&&<div className="assistant-inspector-content"><header><strong>{panelOptions.find(p=>p.id===panel)?.label}</strong><ToolButton label="Свернуть панель" onClick={()=>setPanel(null)}><X size={15}/></ToolButton></header>{panel==="sources"?(sources.length?sources.map((s,index)=><button id={`assistant-source-${index+1}`} type="button" className={`assistant-source ${highlightedSource===index+1?"is-highlighted":""}`} key={s.id} onClick={()=>onOpenCall(s.call_uuid)}><b>{s.call_title}</b><span>{s.quote}</span><small>{s.source_kind==="analysis"?"Анализ":"Транскрипция"} · Версия {s.transcription_revision}</small></button>):<p>Здесь появятся подтверждения из найденных звонков.</p>):context.length?context.map(c=><div className="assistant-attached-item" key={c.id}><Paperclip size={15}/>{c.label}</div>):<p>Добавьте звонки, папки или источники другого чата через + или @.</p>}</div>}</aside>}
 </div></section>;
}
