import { AlertTriangle, ArrowLeft, CalendarClock, CheckCircle2, ChevronDown, ChevronRight, ChevronUp, Clock3, ExternalLink, PlugZap, Search, Send, ShieldCheck, UserRound, X, XCircle } from "lucide-react";
import { FormEvent, MouseEvent as ReactMouseEvent, useDeferredValue, useEffect, useMemo, useState } from "react";
import { ApiError, api } from "../../api";
import type { ActionExternalSync, ActionExternalSyncPreview, AnalysisResponse, CallAction, CallActionAssignee, CallResponse, CompanyResponse, DepartmentResponse, TranscriptionResponse, TranscriptionSpeakerAssignment } from "../../types";
import { useEscapeDismiss } from "../../shared/ui/dismissible-layer";
import { useWorkspaceCompanyId } from "../../shared/lib/workspace-company";
import { FrozenRegion } from "../../shared/ui/frozen-region";
import { TranscriptPreview } from "../../shared/ui/call";
import { DateTimePicker } from "../../shared/ui/DateTimePicker";
import { SelectControl } from "../../shared/ui/primitives";

const statusLabels: Record<string, string> = { open: "Открыто", in_progress: "В работе", completed: "Выполнено", cancelled: "Отменено", overdue: "Просрочено" };

export function ActionsPage({ onOpen }: { onOpen: (id: string) => void }) {
  const [items, setItems] = useState<CallAction[]>([]);
  const [status, setStatus] = useState("");
  const [query, setQuery] = useState("");
  const deferredQuery = useDeferredValue(query);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  // The page is read in the workspace the header points at: a company shows that
  // company's actions, the personal workspace shows the ones that belong to no
  // company at all.
  const workspaceCompanyId = useWorkspaceCompanyId();
  useEffect(() => { let cancelled = false; setLoading(true); api.listActions({ status: status || undefined, q: deferredQuery.trim() || undefined, company_uuid: workspaceCompanyId || undefined, limit: 100 }).then((result) => { if (!cancelled) { setItems(workspaceCompanyId ? result.items : result.items.filter((item) => !item.company_uuid)); setError(""); } }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Не удалось загрузить действия"); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [deferredQuery, status, workspaceCompanyId]);
  return <section className="actions-page atmospheric-page"><header className="actions-hero glass"><div><span className="eyebrow">РАБОЧИЙ ПОТОК</span><h1>Действия</h1><p>Задачи, созданные по итогам разговоров, с ответственными и контролем срока.</p></div></header><div className="actions-toolbar glass"><label className="actions-search"><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Найти действие или ответственного"/></label><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Статус действия"><option value="">Все статусы</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{error ? <div className="form-error">{error}</div> : null}<div className="actions-list glass">{loading ? <p className="actions-empty">Загружаю действия…</p> : items.length === 0 ? <p className="actions-empty">Подходящих действий пока нет.</p> : items.map((item)=><button className="action-row" type="button" key={item.id} onClick={()=>onOpen(item.id)}><span className={`action-status action-status-${item.status}`}>{statusLabels[item.status] ?? item.status}</span><span className="action-row-main"><strong>{item.title}</strong><small>{usernameLabel(item.assignee_username)} · до {formatDateTime(item.due_at)}</small></span><ChevronRight size={18}/></button>)}</div></section>;
}

export function ActionDetailPage({ actionId, onBack, onOpenEvidence }: { actionId: string; onBack: () => void; onOpenEvidence: (action:CallAction,evidence:CallAction["evidence"][number])=>void }) {
  const [item, setItem] = useState<CallAction>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [editingFields,setEditingFields]=useState(false); const [draftTitle,setDraftTitle]=useState(""); const [draftDescription,setDraftDescription]=useState(""); const [reason, setReason] = useState(""); const [dueAt,setDueAt]=useState(""); const [assignees,setAssignees]=useState<CallActionAssignee[]>([]); const [assigneeId,setAssigneeId]=useState(""); const [departmentId,setDepartmentId]=useState("");
	const [syncPreview,setSyncPreview]=useState<ActionExternalSyncPreview>(); const [externalSync,setExternalSync]=useState<ActionExternalSync>(); const [selectedConnectionId,setSelectedConnectionId]=useState(""); const [syncBusy,setSyncBusy]=useState(false); const [syncError,setSyncError]=useState(""); const [rejectComment,setRejectComment]=useState(""); const [resolutionReason,setResolutionReason]=useState(""); const [externalTaskId,setExternalTaskId]=useState("");
  useEffect(()=>{let cancelled=false;api.getAction(actionId).then((result)=>{if(cancelled)return;setItem(result);setDueAt(toLocalDateTime(result.due_at));setAssigneeId(result.assignee_user_uuid);setDepartmentId(result.target_department_uuid??"");if(result.company_uuid&&result.capabilities.can_reassign)api.listActionAssignees(result.company_uuid).then((response)=>{if(!cancelled)setAssignees(response.items)}).catch(()=>{if(!cancelled)setAssignees([])})}).catch((cause)=>{if(!cancelled)setError(cause instanceof Error?cause.message:"Не удалось загрузить действие")});return()=>{cancelled=true}},[actionId]);
	useEffect(()=>{let cancelled=false;Promise.allSettled([api.previewActionExternalSync(actionId),api.getActionExternalSync(actionId)]).then(([previewResult,syncResult])=>{if(cancelled)return;if(previewResult.status==="fulfilled"){setSyncPreview(previewResult.value);const firstAvailable=previewResult.value.options.find((option)=>option.available);setSelectedConnectionId((current)=>current||firstAvailable?.connection_uuid||"")}else if(!(previewResult.reason instanceof ApiError&&previewResult.reason.status===404)){setSyncError(previewResult.reason instanceof Error?previewResult.reason.message:"Не удалось проверить подключение Bitrix24")}if(syncResult.status==="fulfilled")setExternalSync(syncResult.value);else if(!(syncResult.reason instanceof ApiError&&syncResult.reason.status===404)){setSyncError(syncResult.reason instanceof Error?syncResult.reason.message:"Не удалось загрузить статус отправки")}});return()=>{cancelled=true}},[actionId]);
	useEffect(()=>{if(!externalSync||!(externalSync.state==="queued"||externalSync.state==="sending"||externalSync.state==="reconciling"||(externalSync.state==="synced"&&!externalSync.review_state)))return;const delay=externalSync.state==="synced"?15_000:2_500;const timer=window.setInterval(()=>{api.getActionExternalSync(actionId).then(setExternalSync).catch(()=>undefined)},delay);return()=>window.clearInterval(timer)},[actionId,externalSync?.state,externalSync?.review_state]);
  async function mutate(operation:"start"|"complete"|"cancel"|"reschedule"|"reassign"|"revert-status") { if(!item||busy)return;const needsReason=operation==="cancel"||operation==="reschedule"||operation==="reassign";if(needsReason&&reason.trim().length<10){setError("Укажите причину изменения не короче 10 символов");return}setBusy(true);setError("");try{const updated=await api.mutateAction(item.id,operation,{expected_lock_version:item.lock_version,reason:reason.trim(),...(operation==="reschedule"?{due_at:new Date(dueAt).toISOString()}:{}),...(operation==="reassign"?{assignee_user_uuid:assigneeId,target_department_uuid:departmentId}:{})});setItem(updated);setDueAt(toLocalDateTime(updated.due_at));setAssigneeId(updated.assignee_user_uuid);setDepartmentId(updated.target_department_uuid??"");setReason("")}catch(cause){setError(cause instanceof Error?cause.message:"Не удалось изменить действие")}finally{setBusy(false)} }
	async function saveFields(){if(!item||busy)return;setBusy(true);setError("");try{const updated=await api.editAction(item.id,{expected_lock_version:item.lock_version,title:draftTitle.trim(),description:draftDescription.trim()});setItem(updated);setEditingFields(false)}catch(cause){setError(cause instanceof Error?cause.message:"Не удалось изменить формулировку")}finally{setBusy(false)}}	async function requestExternalSync(){if(!selectedConnectionId||syncBusy)return;setSyncBusy(true);setSyncError("");try{setExternalSync(await api.createActionExternalSync(actionId,selectedConnectionId))}catch(cause){setSyncError(cause instanceof Error?cause.message:"Не удалось отправить запрос на согласование")}finally{setSyncBusy(false)}}
	async function decideExternalSync(decision:"approve"|"reject"){if(!externalSync||syncBusy)return;if(decision==="reject"&&rejectComment.trim().length<3){setSyncError("Укажите причину отклонения не короче 3 символов");return}setSyncBusy(true);setSyncError("");try{if(decision==="approve")setExternalSync(await api.approveActionExternalSync(externalSync.sync_uuid,externalSync.lock_version));else{await api.rejectActionExternalSync(externalSync.sync_uuid,externalSync.lock_version,rejectComment.trim());setExternalSync(await api.getActionExternalSync(actionId));setRejectComment("")}}catch(cause){setSyncError(cause instanceof Error?cause.message:"Не удалось сохранить решение")}finally{setSyncBusy(false)}}
	async function resolveExternalSync(resolution:"retry_create"|"cancel"|"confirm_task"|"accept_external"|"unlink"|"restore_verbatrace"){if(!externalSync||syncBusy)return;if(resolutionReason.trim().length<10){setSyncError("Укажите причину решения не короче 10 символов");return}if(resolution==="confirm_task"&&!/^\d{1,20}$/.test(externalTaskId.trim())){setSyncError("Укажите числовой ID задачи Bitrix24");return}setSyncBusy(true);setSyncError("");try{const updated=await api.resolveActionExternalSync(externalSync.sync_uuid,externalSync.lock_version,resolution,resolutionReason.trim(),externalTaskId.trim()||undefined);setExternalSync(updated);setResolutionReason("");setExternalTaskId("")}catch(cause){setSyncError(cause instanceof Error?cause.message:"Не удалось сохранить решение конфликта")}finally{setSyncBusy(false)}}
  if(error&&!item)return <section className="action-detail-page"><button className="text-button" onClick={onBack}>← К действиям</button><div className="form-error">{error}</div></section>; if(!item)return <section className="action-detail-page"><p>Загружаю действие…</p></section>;
  const terminal=item.status==="completed"||item.status==="cancelled";
  const canFinish=item.capabilities.can_complete&&!terminal;
  const canStart=item.capabilities.can_start&&item.status==="open";
  const canCancel=item.capabilities.can_cancel&&!terminal;
  const selectedAssignee=assignees.find((candidate)=>candidate.user_uuid===assigneeId);
  return <FrozenRegion
    frozen={item.call_in_bin}
    message="Звонок помещён в корзину. Действие доступно для чтения, изменения вернутся вместе со звонком."
  >
  <section className="action-detail-page atmospheric-page">
    <button className="text-button action-back" type="button" onClick={onBack} data-frozen-allow><ArrowLeft size={16}/>К действиям</button>
    <header className="action-detail-head glass">
      <div className="action-detail-title"><span className={`action-status action-status-${item.status}`}>{statusLabels[item.status]}</span>{editingFields?<><input aria-label="Название действия" value={draftTitle} maxLength={200} onChange={(event)=>setDraftTitle(event.target.value)}/><textarea aria-label="Описание действия" value={draftDescription} maxLength={10000} onChange={(event)=>setDraftDescription(event.target.value)}/><div className="panel-actions"><button className="primary-button small" type="button" disabled={busy||!draftTitle.trim()} onClick={()=>void saveFields()}>Сохранить</button><button className="ghost-button small" type="button" disabled={busy} onClick={()=>{setEditingFields(false);setDraftTitle(item.title);setDraftDescription(item.description)}}>Отмена</button></div></>:<><h1>{item.title}</h1>{item.description.trim() && <p>{item.description.trim()}</p>}{item.capabilities.can_edit_fields?<button className="text-button" type="button" onClick={()=>{setEditingFields(true);setDraftTitle(item.title);setDraftDescription(item.description)}}>Изменить формулировку</button>:null}</>}</div>
      <aside className="action-detail-meta" aria-label="Сведения о задаче"><div><UserRound size={19}/><span><small>Ответственный</small><strong>{usernameLabel(item.assignee_username)}</strong></span></div><div><CalendarClock size={19}/><span><small>Срок выполнения</small><strong>{formatDateTime(item.due_at)}</strong></span></div></aside>
    </header>
    {error?<div className="form-error">{error}</div>:null}
    <div className="action-detail-grid">
      <section className="action-panel action-evidence-panel glass"><h2>Основание задачи</h2>{item.evidence.length===0?<p className="muted">Цитаты не приложены.</p>:item.evidence.map((e)=><blockquote key={e.id}><button className="action-evidence-link" type="button" onClick={()=>onOpenEvidence(item,e)}><p>{e.quote}</p><small>{e.speaker?`${e.speaker} · `:""}{typeof e.start_seconds==="number"?formatSeconds(e.start_seconds):"Открыть в транскрипции"}</small><span>Перейти к цитате <ChevronRight size={15}/></span></button></blockquote>)}</section>
	  {(syncPreview||externalSync)?<ActionExternalSyncPanel preview={syncPreview} sync={externalSync} selectedConnectionId={selectedConnectionId} busy={syncBusy} error={syncError} rejectComment={rejectComment} resolutionReason={resolutionReason} externalTaskId={externalTaskId} onSelectConnection={setSelectedConnectionId} onRequest={requestExternalSync} onDecision={decideExternalSync} onRejectComment={setRejectComment} onResolutionReason={setResolutionReason} onExternalTaskId={setExternalTaskId} onResolve={resolveExternalSync}/>:null}
      <section className="action-panel action-management-panel glass"><div className="action-management-heading"><div><span className="eyebrow">УПРАВЛЕНИЕ</span><h2>Статус задачи</h2></div><span className={`action-status action-status-${item.status}`}>{statusLabels[item.status]}</span></div><div className="action-progress"><span className={item.status!=="open"?"done":"active"}>1</span><i/><span className={item.status==="completed"?"done":item.status==="in_progress"||item.status==="overdue"?"active":""}>2</span><i/><span className={item.status==="completed"?"done":""}>3</span></div><div className="action-progress-labels"><small>Открыто</small><small>В работе</small><small>Выполнено</small></div><div className="action-close-help">{item.status==="completed"?<><CheckCircle2 size={20}/><span><strong>Задача выполнена</strong><small>Дополнительных действий не требуется.</small></span></>:item.status==="cancelled"?<><XCircle size={20}/><span><strong>Задача отменена</strong><small>{item.cancel_reason||"Причина не указана"}</small></span></>:canFinish?<><CheckCircle2 size={20}/><span><strong>Как закрыть задачу?</strong><small>После фактического выполнения нажмите «Отметить выполненной».</small></span></>:<><Clock3 size={20}/><span><strong>Ожидается выполнение</strong><small>Закрыть задачу может ответственный, лидер исходного или целевого отдела либо менеджер компании.</small></span></>}</div><div className="action-controls">{canStart?<button className="ghost-button action-start-button" type="button" disabled={busy} onClick={()=>void mutate("start")}><Clock3 size={18}/>{busy?"Обновляю…":"Начать выполнение"}</button>:null}{canFinish?<button className="primary-button action-complete-button" type="button" disabled={busy} onClick={()=>void mutate("complete")}><CheckCircle2 size={18}/>{busy?"Закрываю…":"Отметить выполненной"}</button>:null}{canCancel?<div className="action-cancel-control"><label htmlFor="action-cancel-reason">Отмена задачи <small>Только если задача ошибочная или потеряла актуальность.</small></label><textarea id="action-cancel-reason" value={reason} maxLength={2000} onChange={(event)=>setReason(event.target.value)} placeholder="Укажите причину отмены — минимум 10 символов"/><button className="ghost-button danger" type="button" disabled={busy||reason.trim().length<10} onClick={()=>void mutate("cancel")}><XCircle size={17}/>Отменить задачу</button></div>:null}</div></section>
      {(item.capabilities.can_reschedule||item.capabilities.can_reassign||item.capabilities.can_revert_status)?<ActionCorrectionControls item={item} busy={busy} reason={reason} dueAt={dueAt} assignees={assignees} assigneeId={assigneeId} departmentId={departmentId} onReason={(value)=>{setReason(value);setError("")}} onDueAt={setDueAt} onAssignee={(value)=>{setAssigneeId(value);const person=assignees.find((candidate)=>candidate.user_uuid===value);setDepartmentId(person?.departments[0]?.id??"")}} onDepartment={setDepartmentId} onMutate={mutate}/>:null}
    </div>
  </section>
  </FrozenRegion>;
}

type ExternalSyncResolution = "retry_create"|"cancel"|"confirm_task"|"accept_external"|"unlink"|"restore_verbatrace";

function ActionExternalSyncPanel({preview,sync,selectedConnectionId,busy,error,rejectComment,resolutionReason,externalTaskId,onSelectConnection,onRequest,onDecision,onRejectComment,onResolutionReason,onExternalTaskId,onResolve}:{preview?:ActionExternalSyncPreview;sync?:ActionExternalSync;selectedConnectionId:string;busy:boolean;error:string;rejectComment:string;resolutionReason:string;externalTaskId:string;onSelectConnection:(value:string)=>void;onRequest:()=>Promise<void>;onDecision:(decision:"approve"|"reject")=>Promise<void>;onRejectComment:(value:string)=>void;onResolutionReason:(value:string)=>void;onExternalTaskId:(value:string)=>void;onResolve:(resolution:ExternalSyncResolution)=>Promise<void>}){
	const selected=preview?.options.find((option)=>option.connection_uuid===selectedConnectionId);
	return <section className="action-panel action-external-sync-panel glass" aria-labelledby="bitrix-sync-title">
		<header><span className="action-external-sync-icon"><PlugZap size={20}/></span><div><span className="eyebrow">ИНТЕГРАЦИЯ</span><h2 id="bitrix-sync-title">Задача в Bitrix24</h2></div>{sync?<span className={`external-sync-state external-sync-state-${sync.state}`}>{externalSyncStateLabel(sync.state)}</span>:null}</header>
		{sync?<ExternalSyncStatus sync={sync}/>:<>
			<p className="action-external-sync-intro">Передача выполняется только после подтверждения руководителя. Запись звонка, транскрипция и внутренние цитаты в Bitrix24 не отправляются.</p>
			{preview?.options.length?<><label>Подключение<SelectControl aria-label="Подключение Bitrix24" value={selectedConnectionId} onChange={(event)=>onSelectConnection(event.target.value)}>{preview.options.map((option)=><option key={option.connection_uuid} value={option.connection_uuid} disabled={!option.available}>{option.connection_name}{option.available?` · ${option.portal_domain}`:" · не сопоставлен ответственный"}</option>)}</SelectControl></label>{selected?<dl className="external-sync-preview"><div><dt>Название</dt><dd>{preview.title}</dd></div><div><dt>Срок</dt><dd>{formatDateTime(preview.due_at)}</dd></div><div><dt>Портал</dt><dd>{selected.portal_domain}</dd></div><div><dt>Ответственный</dt><dd>{selected.available?`Bitrix24 ID ${selected.external_assignee_id}`:"Не сопоставлен"}</dd></div></dl>:null}<button className="primary-button" type="button" disabled={busy||!selected?.available} onClick={()=>void onRequest()}><Send size={17}/>{busy?"Создаю запрос…":"Запросить отправку"}</button></>:<div className="external-sync-empty"><AlertTriangle size={19}/><span><strong>Нет готового подключения</strong><small>Менеджеру компании нужно подключить Bitrix24 и сопоставить ответственного.</small></span></div>}
		</>}
		{sync?.state==="pending_approval"&&sync.can_approve?<div className="external-sync-approval"><div><ShieldCheck size={19}/><span><strong>Нужно ваше решение</strong><small>Проверьте задачу и подтвердите создание в Bitrix24.</small></span></div><button className="primary-button" type="button" disabled={busy} onClick={()=>void onDecision("approve")}><CheckCircle2 size={17}/>Подтвердить</button><label>Причина отклонения<textarea value={rejectComment} maxLength={1000} onChange={(event)=>onRejectComment(event.target.value)} placeholder="Кратко объясните причину"/></label><button className="ghost-button danger" type="button" disabled={busy||rejectComment.trim().length<3} onClick={()=>void onDecision("reject")}><XCircle size={17}/>Отклонить</button></div>:null}
		{sync?.can_resolve&&(sync.state==="needs_review"||sync.review_state)?<ExternalSyncResolutionPanel sync={sync} busy={busy} reason={resolutionReason} externalTaskId={externalTaskId} onReason={onResolutionReason} onExternalTaskId={onExternalTaskId} onResolve={onResolve}/>:null}
		{error?<div className="form-error" role="alert">{error}</div>:null}
	</section>
}

function ExternalSyncStatus({sync}:{sync:ActionExternalSync}){
	if(sync.state==="synced"&&sync.review_state)return <div className="external-sync-result warning"><AlertTriangle size={20}/><span><strong>Задача в Bitrix24 изменилась</strong><small>{externalSyncReviewLabel(sync.review_reason)}</small>{sync.last_checked_at?<small>Проверено: {formatDateTime(sync.last_checked_at)}</small>:null}</span></div>;
	if(sync.state==="synced")return <div className="external-sync-result success"><CheckCircle2 size={20}/><span><strong>Задача создана в Bitrix24</strong><small>{sync.external_task_id?`ID задачи: ${sync.external_task_id}`:"Bitrix24 подтвердил создание задачи."}</small>{sync.external_task_url?<a href={sync.external_task_url} target="_blank" rel="noreferrer">Открыть в Bitrix24 <ExternalLink size={14}/></a>:null}{sync.last_checked_at?<small>Последняя проверка: {formatDateTime(sync.last_checked_at)}</small>:null}</span></div>;
	if(sync.state==="rejected")return <div className="external-sync-result danger"><XCircle size={20}/><span><strong>Отправка отклонена</strong><small>Новая отправка возможна после изменения задачи или решения руководителя.</small></span></div>;
	if(sync.state==="reconciling"||sync.state==="needs_review")return <div className="external-sync-result warning"><AlertTriangle size={20}/><span><strong>Требуется проверка результата</strong><small>Ответ Bitrix24 был неоднозначным. VerbaTrace не создаёт задачу повторно, чтобы избежать дубля.</small></span></div>;
	if(sync.state==="failed")return <div className="external-sync-result danger"><AlertTriangle size={20}/><span><strong>Отправка не выполнена</strong><small>Код ошибки: {sync.last_error_code??"unknown"}. Обратитесь к менеджеру интеграции.</small></span></div>;
	return <div className="external-sync-result pending"><Clock3 size={20}/><span><strong>{sync.state==="pending_approval"?"Ожидается подтверждение руководителя":"Задача отправляется"}</strong><small>{sync.state==="pending_approval"?"После подтверждения VerbaTrace создаст задачу автоматически.":"Статус обновится автоматически."}</small></span></div>;
}

function ExternalSyncResolutionPanel({sync,busy,reason,externalTaskId,onReason,onExternalTaskId,onResolve}:{sync:ActionExternalSync;busy:boolean;reason:string;externalTaskId:string;onReason:(value:string)=>void;onExternalTaskId:(value:string)=>void;onResolve:(resolution:ExternalSyncResolution)=>Promise<void>}){
	const ambiguous=sync.state==="needs_review"&&!sync.external_task_id;
	const validReason=reason.trim().length>=10;
	return <div className="external-sync-resolution" aria-label="Разрешение конфликта синхронизации">
		<div className="external-sync-resolution-head"><ShieldCheck size={19}/><span><strong>Решение принимает руководитель</strong><small>Выберите источник истины. Действие и причина сохранятся в истории.</small></span></div>
		{!ambiguous&&sync.external_snapshot?<dl className="external-sync-snapshot"><div><dt>Название в Bitrix24</dt><dd>{sync.external_snapshot.title||"Не указано"}</dd></div><div><dt>Статус</dt><dd>{externalTaskStatusLabel(sync.external_snapshot.status)}</dd></div><div><dt>Срок</dt><dd>{sync.external_snapshot.deadline?formatDateTime(sync.external_snapshot.deadline):"Не указан"}</dd></div><div><dt>Ответственный</dt><dd>{sync.external_snapshot.responsible_id?`Bitrix24 ID ${sync.external_snapshot.responsible_id}`:"Не указан"}</dd></div></dl>:null}
		<label>Причина решения <small>Обязательно, минимум 10 символов.</small><textarea value={reason} maxLength={2000} onChange={(event)=>onReason(event.target.value)} placeholder="Почему выбран этот вариант"/></label>
		{ambiguous?<><label>ID уже созданной задачи <small>Если задача всё же появилась в Bitrix24, укажите её числовой ID.</small><input inputMode="numeric" maxLength={20} value={externalTaskId} onChange={(event)=>onExternalTaskId(event.target.value.replace(/\D/g,""))} placeholder="Например, 1542"/></label><div className="external-sync-resolution-actions"><button className="primary-button" type="button" disabled={busy||!validReason||!/^\d{1,20}$/.test(externalTaskId)} onClick={()=>void onResolve("confirm_task")}><CheckCircle2 size={17}/>Связать найденную задачу</button><button className="ghost-button" type="button" disabled={busy||!validReason} onClick={()=>void onResolve("retry_create")}><Send size={17}/>Повторить создание</button><button className="ghost-button danger" type="button" disabled={busy||!validReason} onClick={()=>void onResolve("cancel")}><XCircle size={17}/>Отменить отправку</button></div><small className="external-sync-duplicate-warning">Повторяйте создание только после проверки портала: при неоднозначном ответе задача могла быть создана.</small></>:<div className="external-sync-resolution-actions"><button className="primary-button" type="button" disabled={busy||!validReason} onClick={()=>void onResolve("accept_external")}><CheckCircle2 size={17}/>Принять данные Bitrix24</button><button className="ghost-button" type="button" disabled={busy||!validReason} onClick={()=>void onResolve("restore_verbatrace")}><Send size={17}/>Вернуть данные VerbaTrace</button><button className="ghost-button danger" type="button" disabled={busy||!validReason} onClick={()=>void onResolve("unlink")}><XCircle size={17}/>Разорвать связь</button></div>}
	</div>
}

function externalSyncReviewLabel(reason?:string|null){return({external_task_missing:"Задача удалена или недоступна в Bitrix24.",external_task_completed:"Задача завершена в Bitrix24, но действие VerbaTrace ещё открыто.",external_task_fields_changed:"Название, срок или ответственный отличаются от VerbaTrace.",external_task_status_changed:"Статус задачи отличается от VerbaTrace."} as Record<string,string>)[reason??""]??"Данные Bitrix24 расходятся с VerbaTrace."}
function externalTaskStatusLabel(status?:string){return({pending:"Ждёт выполнения",in_progress:"В работе",completed:"Выполнено",deferred:"Отложено",declined:"Отклонено"} as Record<string,string>)[status??""]??(status||"Не указан")}

function externalSyncStateLabel(state:ActionExternalSync["state"]){return({pending_approval:"На согласовании",rejected:"Отклонено",queued:"В очереди",sending:"Отправляется",reconciling:"Проверка",needs_review:"Нужна проверка",synced:"Создано",failed:"Ошибка",cancelled:"Отменено",unlinked:"Связь удалена"} as Record<ActionExternalSync["state"],string>)[state]}

function ActionCorrectionControls({item,busy,reason,dueAt,assignees,assigneeId,departmentId,onReason,onDueAt,onAssignee,onDepartment,onMutate}:{item:CallAction;busy:boolean;reason:string;dueAt:string;assignees:CallActionAssignee[];assigneeId:string;departmentId:string;onReason:(value:string)=>void;onDueAt:(value:string)=>void;onAssignee:(value:string)=>void;onDepartment:(value:string)=>void;onMutate:(operation:"reschedule"|"reassign"|"revert-status")=>Promise<void>}){
  const selected=assignees.find((candidate)=>candidate.user_uuid===assigneeId);const validReason=reason.trim().length>=10;
  return <section className="action-panel action-correction-panel glass"><h2>Настройка действия</h2><label>Причина изменения<small>Обязательна, минимум 10 символов.</small><textarea value={reason} maxLength={2000} onChange={(event)=>onReason(event.target.value)} placeholder="Причина изменения"/></label>{item.capabilities.can_reassign&&item.company_uuid?<><label>Ответственный<SelectControl aria-label="Ответственный" value={assigneeId} onChange={(event)=>onAssignee(event.target.value)}>{assignees.map((person)=><option key={person.user_uuid} value={person.user_uuid}>{usernameLabel(person.username)} · {person.full_name} {person.full_surname}</option>)}</SelectControl></label><label>Отдел<SelectControl aria-label="Отдел" value={departmentId} onChange={(event)=>onDepartment(event.target.value)}>{selected?.departments.map((department)=><option key={department.id} value={department.id}>{department.name}</option>)}</SelectControl></label><button className="ghost-button" type="button" disabled={busy||!validReason||!assigneeId||!departmentId} onClick={()=>void onMutate("reassign")}><UserRound size={17}/>Переназначить</button></>:null}{item.capabilities.can_reschedule?<><label>Новый срок<DateTimePicker value={dueAt} onChange={onDueAt}/></label><button className="ghost-button" type="button" disabled={busy||!validReason||!dueAt} onClick={()=>void onMutate("reschedule")}><CalendarClock size={17}/>Изменить срок</button></>:null}{item.capabilities.can_revert_status?<><p className="muted">Смену статуса можно откатить в течение часа.</p><button className="ghost-button" type="button" disabled={busy} onClick={()=>void onMutate("revert-status")}><Clock3 size={17}/>Вернуть прежний статус</button></>:null}</section>
}

export function CreateActionDialog({ call, analysis, transcription, speakerAssignments, companies, departments, currentUserId, onClose, onCreated }: { call: CallResponse; analysis: AnalysisResponse; transcription?: TranscriptionResponse; speakerAssignments?: TranscriptionSpeakerAssignment[]; companies: CompanyResponse[]; departments: DepartmentResponse[]; currentUserId: string; onClose:()=>void; onCreated:(action:CallAction)=>void }) {
  const companyId=call.company_uuid??""; const availableDepartments=departments.filter((d)=>d.company_uuid===companyId); const [title,setTitle]=useState(()=>nextStep(analysis)); const [description,setDescription]=useState(""); const [sourceDepartment,setSourceDepartment]=useState(call.department_uuid??availableDepartments[0]?.id??""); const [targetDepartment,setTargetDepartment]=useState(call.department_uuid??availableDepartments[0]?.id??""); const [assignee,setAssignee]=useState(""); const [assignees,setAssignees]=useState<CallActionAssignee[]>([]); const [assigneeQuery,setAssigneeQuery]=useState(""); const [assigneeResultsOpen,setAssigneeResultsOpen]=useState(false); const deferredAssigneeQuery=useDeferredValue(assigneeQuery); const [dueAt,setDueAt]=useState(""); const [quoteQuery,setQuoteQuery]=useState(""); const [fullTranscriptOpen,setFullTranscriptOpen]=useState(false); const [pendingRange,setPendingRange]=useState<{start:number;end:number}|null>(null); const [selectedRanges,setSelectedRanges]=useState<Array<{start:number;end:number}>>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEscapeDismiss(!busy, onClose);
  useEffect(()=>{if(!companyId)return;let cancelled=false;api.listActionAssignees(companyId,{q:deferredAssigneeQuery.trim()||undefined}).then((result)=>{if(!cancelled)setAssignees(result.items.filter((item)=>item.user_uuid!==currentUserId))}).catch(()=>{if(!cancelled)setAssignees([])});return()=>{cancelled=true}},[companyId,currentUserId,deferredAssigneeQuery]); const matches=useMemo(()=>findMatches(transcription?.words??[],quoteQuery),[quoteQuery,transcription?.words]);
  function chooseAssignee(user:CallActionAssignee){setAssignee(user.user_uuid);setAssigneeQuery(usernameLabel(user.username));setAssigneeResultsOpen(false);if(user.departments.length===1)setTargetDepartment(user.departments[0].id);else if(!user.departments.some((d)=>d.id===targetDepartment))setTargetDepartment("")}
  function captureTranscriptSelection(event:ReactMouseEvent<HTMLDivElement>){const selection=window.getSelection();if(!selection||selection.isCollapsed||selection.rangeCount===0){setPendingRange(null);return}const start=wordIndexFromNode(selection.anchorNode);const end=wordIndexFromNode(selection.focusNode);if(start===null||end===null||!event.currentTarget.contains(selection.anchorNode)||!event.currentTarget.contains(selection.focusNode)){setPendingRange(null);return}setPendingRange({start:Math.min(start,end),end:Math.max(start,end)})}
  function addPendingQuote(){if(!pendingRange)return;setSelectedRanges((current)=>{if(current.some((range)=>range.start===pendingRange.start&&range.end===pendingRange.end))return current;if(current.length>=20){setError("К одному действию можно добавить не более 20 цитат");return current}return[...current,pendingRange]});setPendingRange(null);window.getSelection()?.removeAllRanges()}
  function toggleQuote(range:{start:number;end:number}){setSelectedRanges((current)=>{const selected=current.some((item)=>item.start===range.start&&item.end===range.end);if(selected)return current.filter((item)=>item.start!==range.start||item.end!==range.end);if(current.length>=20){setError("К одному действию можно добавить не более 20 цитат");return current}setError("");return[...current,range]})}
  function removeQuote(range:{start:number;end:number}){setSelectedRanges((current)=>current.filter((item)=>item.start!==range.start||item.end!==range.end));if(pendingRange?.start===range.start&&pendingRange.end===range.end)setPendingRange(null)}
  async function submit(event:FormEvent){event.preventDefault();if(!analysis.id){setError("Для создания действия нужен готовый анализ");return}if(!dueAt){setError("Укажите срок выполнения действия");return}const effectiveAssignee=companyId?(assignee||call.uploaded_by_user_uuid||""):(call.uploaded_by_user_uuid||currentUserId);if(!effectiveAssignee){setError("Не удалось определить ответственного: у звонка не указан владелец");return}setBusy(true);setError("");try{const action=await api.createAction(call.id,{analysis_uuid:analysis.id,...(companyId?{source_department_uuid:sourceDepartment,target_department_uuid:targetDepartment,assignee_user_uuid:effectiveAssignee}:{}),title:title.trim(),description:description.trim(),due_at:new Date(dueAt).toISOString(),evidence:selectedRanges.map((range)=>({word_start_index:range.start,word_end_index:range.end}))});onCreated(action)}catch(cause){setError(cause instanceof Error?cause.message:"Не удалось создать действие")}finally{setBusy(false)}} const chosen=assignees.find((item)=>item.user_uuid===assignee);
  return <div className="action-dialog-layer" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!busy)onClose()}}>
    <div className="action-dialog-frame glass">
    <form className="action-dialog" role="dialog" aria-modal="true" aria-labelledby="create-action-title" onSubmit={(event)=>void submit(event)}>
      <header><div><span className="eyebrow">ПО ИТОГАМ ЗВОНКА</span><h2 id="create-action-title">Создать действие</h2></div><button className="icon-button" type="button" aria-label="Закрыть" onClick={onClose}><X size={18}/></button></header>
      <label>Название<input required maxLength={200} value={title} onChange={(event)=>setTitle(event.target.value)}/></label>
      <label>Описание<textarea maxLength={10000} value={description} onChange={(event)=>setDescription(event.target.value)}/></label>
      <div className="action-form-grid">{companyId?<label>Исходный отдел<select required value={sourceDepartment} onChange={(event)=>setSourceDepartment(event.target.value)}>{availableDepartments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>:null}<label htmlFor="action-due-at">Срок<DateTimePicker id="action-due-at" required value={dueAt} onChange={setDueAt}/></label></div>
      {companyId?<label className="action-assignee-search" onBlur={(event)=>{if(!event.currentTarget.contains(event.relatedTarget as Node|null))setAssigneeResultsOpen(false)}}>
        Ответственный
        <small className="action-field-hint">Необязательно. Если никого не выбрать, ответственным станет пользователь, загрузивший звонок.</small>
        <input value={assigneeQuery} onFocus={()=>setAssigneeResultsOpen(true)} onChange={(event)=>{setAssigneeQuery(event.target.value);setAssignee("");setAssigneeResultsOpen(true)}} placeholder="@username или имя"/>
        {assigneeResultsOpen&&!assignee?<div className="action-assignee-results">{assignees.length?assignees.map((user)=><button type="button" key={user.user_uuid} onClick={()=>chooseAssignee(user)}><strong>{usernameLabel(user.username)}</strong><small>{user.full_name} {user.full_surname}</small></button>):<small className="action-assignee-empty">Подходящих сотрудников не найдено</small>}</div>:null}
      </label>:null}
      {companyId&&chosen&&chosen.departments.length>1?<label>Целевой отдел<select required value={targetDepartment} onChange={(event)=>setTargetDepartment(event.target.value)}><option value="">Выберите отдел</option>{chosen.departments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>:null}
      <fieldset className="evidence-picker">
        <legend>Цитаты из транскрипции</legend>
        <label><Search size={16}/><input value={quoteQuery} onChange={(event)=>setQuoteQuery(event.target.value)} placeholder="Поиск как Ctrl+F"/></label>
        {quoteQuery?<div className="evidence-search-results"><small>Совпадений: {matches.length}</small>{matches.slice(0,20).map((match)=><button type="button" key={`${match.start}-${match.end}`} className={selectedRanges.some((range)=>range.start===match.start&&range.end===match.end)?"selected":""} onClick={()=>toggleQuote(match)}>{(transcription?.words??[]).slice(match.start,match.end+1).map((word)=>word.text).join(" ")}</button>)}</div>:<small>Введите часть фразы и выберите нужное совпадение.</small>}
        <button className="evidence-transcript-toggle" type="button" aria-expanded={fullTranscriptOpen} onClick={()=>setFullTranscriptOpen((current)=>!current)}><span>{fullTranscriptOpen?"Скрыть полную транскрипцию":"Показать полную транскрипцию"}</span>{fullTranscriptOpen?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>
        {fullTranscriptOpen?<div className="evidence-transcript-selection"><small>Выделите мышью нужные слова в расшифровке.</small><div className="evidence-full-transcript" onMouseUp={captureTranscriptSelection}><TranscriptPreview transcription={transcription} expanded speakerAssignments={speakerAssignments} selectedEvidence={(pendingRange??selectedRanges.at(-1))?{startSeconds:transcription?.words?.[(pendingRange??selectedRanges.at(-1))!.start]?.start_seconds??0,endSeconds:transcription?.words?.[(pendingRange??selectedRanges.at(-1))!.end]?.end_seconds??undefined,wordStartIndex:(pendingRange??selectedRanges.at(-1))!.start,wordEndIndex:(pendingRange??selectedRanges.at(-1))!.end}:null}/></div>{pendingRange?<button className="primary-button evidence-add-selection" type="button" onClick={addPendingQuote}>Добавить выделенное как цитату</button>:null}</div>:null}
        {selectedRanges.length?<div className="selected-evidence-list"><div className="selected-evidence-heading"><strong>Добавленные цитаты</strong><small>{selectedRanges.length}/20</small></div>{selectedRanges.map((range,index)=><div className="selected-evidence-item" key={`${range.start}-${range.end}`}><span><small>Цитата {index+1}</small><p>{(transcription?.words??[]).slice(range.start,range.end+1).map((word)=>word.text).join(" ")}</p></span><button className="icon-button" type="button" aria-label={`Убрать цитату ${index+1}`} title="Убрать цитату" onClick={()=>removeQuote(range)}><X size={17}/></button></div>)}</div>:null}
      </fieldset>
      {error?<div className="form-error">{error}</div>:null}
      <footer><button className="ghost-button" type="button" onClick={onClose}>Отмена</button><button className="primary-button" type="submit" disabled={busy||Boolean(companyId&&!targetDepartment)}>{busy?"Создаю…":"Создать"}</button></footer>
    </form>
    </div>
  </div>;
}

function usernameLabel(username:string){const normalized=username.trim().replace(/^@+/,"");return normalized?`@${normalized}`:""}
function wordIndexFromNode(node:Node|null){const element=node instanceof Element?node:node?.parentElement;const value=element?.closest<HTMLElement>("[data-word-index]")?.dataset.wordIndex;if(value===undefined)return null;const index=Number(value);return Number.isInteger(index)?index:null}

function findMatches(words:TranscriptionResponse["words"],raw:string){const query=raw.trim().toLocaleLowerCase("ru-RU");if(query.length<2)return[];const searchable=words.map((word,index)=>({index,text:word.text.toLocaleLowerCase("ru-RU").replace(/[^\p{L}\p{N}]+/gu,"")})).filter((word)=>word.text);const needle=query.split(/\s+/).map((token)=>token.replace(/[^\p{L}\p{N}]+/gu,"")).filter(Boolean);if(!needle.length)return[];const sentences=new Map<string,{start:number;end:number}>();for(let i=0;i<=searchable.length-needle.length;i+=1){if(!needle.every((token,index)=>searchable[i+index].text.includes(token)))continue;const sentence=sentenceRange(words,searchable[i].index,searchable[i+needle.length-1].index);sentences.set(`${sentence.start}:${sentence.end}`,sentence)}return[...sentences.values()]}
function sentenceRange(words:TranscriptionResponse["words"],matchStart:number,matchEnd:number){let start=matchStart;let end=matchEnd;while(start>0&&!endsSentence(words[start-1].text)&&sameSpeaker(words[start-1].speaker,words[start].speaker))start-=1;while(end<words.length-1&&!endsSentence(words[end].text)&&sameSpeaker(words[end].speaker,words[end+1].speaker))end+=1;return{start,end}}
function endsSentence(text:string){return/[.!?…](?:["'»”’)\]]+)?$/u.test(text.trim())}
function sameSpeaker(left?:string|null,right?:string|null){return(left??"").trim()===(right??"").trim()}
function nextStep(analysis:AnalysisResponse){const result=analysis.result_json;if(!result||typeof result!=="object"||Array.isArray(result))return"";const value=(result as Record<string,unknown>).next_step;return typeof value==="string"?value:""}
function formatDateTime(value:string){return new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function toLocalDateTime(value:string){const date=new Date(value);if(Number.isNaN(date.getTime()))return"";return new Date(date.getTime()-date.getTimezoneOffset()*60_000).toISOString().slice(0,16)}
function formatSeconds(value:number){const minutes=Math.floor(value/60);return`${minutes}:${Math.floor(value%60).toString().padStart(2,"0")}`}
